name: MinGW32 CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@v11
    - uses: DeterminateSystems/magic-nix-cache-action@v6
    - uses: DeterminateSystems/flake-checker-action@v7
    - name: Configure
      run: nix develop --command make -j8 all
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ijl15.dll
        path: out/ijl15.dll
