name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      uses: pangbox/openwatcom-action@master
      with:
        target: all
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ijl15.dll
        path: out/ijl15.dll
